name: Deploy-production

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  deploy:
    if: github.repository == 'redotlabs/client'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REDOT_PRIVATE_PAT }}
          fetch-depth: 0 

      - name: Restore vercel.json from secret
        run: |
          cat << 'EOF' > apps/admin/vercel.json
          ${{ secrets.VERCEL_JSON_PRODUCTION }}
          EOF

      - name: Commit generated vercel.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add apps/admin/vercel.json
          git commit -m "chore: generate vercel.json for deploy" || echo "no changes"

      - name: Push to deploy repository
        run: |
          git remote add deploy https://redot-dev:${{ secrets.REDOT_PRIVATE_PAT }}@github.com/redot-dev/client-deploy.git
          git push --force deploy main
